uri: "amqp://lalala:newspaper@localhost:5672"
#uri: "redis://@localhost:6379"
publishers:
    - topic: "test"
      routing_key: "test"
      concurrency_count: 10000
      message_count: 100
      auto_delete: false
subscribers:
    - topic: "test"
      routing_key: "test"
      auto_delete_exchange: false
      auto_delete_queue: false
      auto_ack: true
